name: Update GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Generate Snake SVG
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: python scripts/fetch_contributions.py
        
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github_contributions_snake.svg
          git commit -m "Update GitHub contribution snake" || exit 0
          git push