name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate Snake
      run: |
        python scripts/github_snake.py
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}

    - name: Commit and Push
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add github-snake.svg
        git commit -m "Update GitHub contribution snake" || exit 0
        git push